version: '3'

services:
  kuzzle:
    image: kuzzleio/howto-massiveimport-kuzzle
    volumes:
      - "./scripts:/scripts"
      - "./etc/kuzzle:/etc/kuzzle"
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "7512:7512"
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=production
      # - DEBUG=kuzzle:plugins

  redis:
    image: redis:3.2

  elasticsearch:
    image: kuzzleio/elasticsearch:5.4.1
    environment:
      - cluster.name=kuzzle
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
